version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=1
 
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: static_frontend
    ports:
      - "5501:80"
    volumes:
      - ./frontend:/usr/share/nginx/html