# Generated by Django 4.2.23 on 2025-07-22 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_asistencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='hora',
            field=models.TimeField(),
        ),
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('usuario', 'fecha', 'tipo')},
        ),
    ]
