# Generated by Django 5.2.4 on 2025-07-24 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_solicituddia'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hora_esperada_entrada',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
