# Generated by Django 4.2.23 on 2025-07-25 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_sucursal_user_sucursales'),
        ('usuarios', '0005_user_hora_esperada_entrada'),
    ]

    operations = [
    ]
