# Generated by Django 4.2.23 on 2025-07-26 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_merge_20250725_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='estado',
            field=models.CharField(blank=True, choices=[('puntual', 'Puntual'), ('tarde', 'Tarde'), ('temprano', 'Temprano'), ('fuera_de_horario', 'Fuera de horario'), ('sin_horario', 'Sin horario'), ('', 'No aplica')], default='', max_length=20),
        ),
    ]
